{% set name = "speclite" %}
{% set version = "0.5" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  number: 0

requirements:
  run:
    - python
    - numpy
    - matplotlib
    - astropy
    - scipy

  build:
    - python
    - setuptools
    - astropy-helpers
    - numpy
    - matplotlib

test:
  imports:
    - speclite

about:
  dev_url: ''
  license: BSD License
  license_family: BSD
  license_file: ''
  doc_url: ''

extra:
  recipe-maintainers: ''
