package:
  name: multinest
  version: "3.10"

source:
  git_url: https://github.com/JohannesBuchner/MultiNest

requirements:
  build:
    - python
    - cmake
    - lapack
    - libgcc [osx]
    - gcc [osx]
    - libgfortran [linux]

  run:
    - python
    - lapack
    - libgcc [osx]
    - libgfortran [linux]

about:
  home: https://github.com/JohannesBuchner/MultiNest

