coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false
  ignore:
    - **/tutorial_material.py
    - threeML/test/.*
    - threeML/plugins/experimental/.*
    - **/__init__.py
comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new


