{% set data = load_setup_py_data() %}

package:
  name: threeml
  version: {{ data.get('version') }}

source:
  #git_url: https://github.com/giacomov/3ML.git
  path: ../../../

build:
   noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml
    - dill
    - iminuit >=1.2
    - astromodels >=0.4
    - corner >=1.0.2
    - pandas
    - html2text
    - requests
    - speclite
    - pymultinest
    - cthreeml
    - ipywidgets
    - ipython <6.0
    - ipyparallel

  run:
    - python
    - setuptools
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml
    - dill
    - iminuit >=1.2
    - astromodels >=0.4
    - corner >=1.0.2
    - pandas
    - html2text
    - requests
    - speclite
    - pymultinest
    - cthreeml
    - ipywidgets
    - ipython <6.0
    - ipyparallel
    - xz

test:
  # Python imports
  imports:
    - threeML
    - threeML.bayesian
    - threeML.catalogs
    - threeML.classicMLE
    - threeML.config
    - threeML.exceptions
    - threeML.io
    - threeML.minimizer
    - threeML.parallel
    - threeML.plugins
    - threeML.utils

about:
  home: https://github.com/giacomov/3ML
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

