{% set name = "threeml" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#    git_url: https://github.com/giacomov/3ML.git
  path: ../../../

build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]
  skip: true  # [py3k]

requirements:
  
  build:
    - python
    - toolchain
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml
    - dill
    - iminuit >=1.2
    - astromodels
    - astroquery
    - corner >=1.0.2
    - pandas
    - requests
    - speclite
    - pymultinest
    - pygmo >=2.4
    - ipywidgets
    - ipython
    - ipyparallel
    - py

  run:
    - python
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml
    - dill
    - iminuit >=1.2
    - astromodels
    - astroquery
    - corner >=1.0.2
    - pandas
    - requests
    - speclite
    - pymultinest
    - pygmo >=2.4
    - ipywidgets
    - ipython
    - ipyparallel
    - xz
    - py

#test:
#  # Python imports
#  commands:
#    - python -c 'import os;os.environ["MPLBACKEND"]="Agg";from threeML import *'


about:
  home: https://github.com/giacomov/3ML
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov

