package:
  name: astromodels
  version: "0.4.1"

source:
  git_url: https://github.com/giacomov/astromodels.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyyaml
    - astropy
    - scipy
    - numdifftools
    - hdf5
    - pytables
    - pandas
    - html2text
    - xspec-modelsonly
  run:
    - python
    - numpy
    - pyyaml
    - astropy
    - scipy
    - numdifftools
    - hdf5
    - pytables
    - pandas
    - html2text
    - xspec-modelsonly
test:
  # Python imports
  imports:
    - astromodels
    - astromodels.core
    - astromodels.functions
    - astromodels.functions.dark_matter
    - astromodels.sources
    - astromodels.utils
    - astromodels.xspec

about:
  home: https://github.com/giacomov/astromodels
  license: BSD-3
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER
