package:
  name: cthreeml
  version: "1.0.3"

source:
  git_url: https://github.com/giacomov/cthreeML.git

requirements:
  build:
    - toolchain
    - python x.x
    - boost <1.65
    - numpy
    - gcc

  run:
    - python x.x
    - boost <1.65
    - numpy
    - libgcc

test:
  commands:
  
    - conda inspect linkages -p $PREFIX cthreeml  # [not win]
    - conda inspect objects -p $PREFIX cthreeml  # [osx]

  imports:
    - cthreeML.pyModelInterfaceCache


about:
  home: https://github.com/threeml/cthreeML
  license: BSD-3
  summary: 'The C/C++ bridge for the Multi-Mission Maximum Likelihood framework (github.com/threeml/threeml)'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov

